# Generated by Django 2.2.1 on 2019-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('sex', models.BinaryField(max_length=1)),
                ('date_reg', models.DateField(auto_now_add=True)),
                ('profile_picture', models.ImageField(upload_to='dir/dir2/dir3')),
            ],
        ),
    ]
