# Generated by Django 2.2.1 on 2019-07-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_modelos', '0002_auto_20190619_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Campo Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Pepe Clabo', max_length=50, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text=' Choose your gender!', max_length=1),
        ),
    ]
