# Generated by Django 3.0.8 on 2020-08-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_fields_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields_types',
            old_name='BAF',
            new_name='BIF',
        ),
    ]
