# Generated by Django 2.2.1 on 2020-06-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='nombre',
            field=models.CharField(default='default_name', max_length=200),
        ),
    ]
