# Generated by Django 2.2.1 on 2020-06-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_owner_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nombre',
            field=models.CharField(default='default_name', max_length=200),
        ),
    ]
