# Generated by Django 2.2.1 on 2019-06-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='static/working_modelos/images/profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=1),
        ),
    ]
